# tasks file
---
- name: repository
  ansible.builtin.import_tasks: repository.yml
  tags:
    - configuration
    - spotify
    - spotify-repository

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - spotify
    - spotify-install
